name: Deploy PR Environment
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    env:
      NAMESPACE: pr${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies UI
        run: npm install
        working-directory: ./frontend

      - name: Run Linter
        run: npm run lint
        working-directory: ./frontend

      - name: Run UI Tests
        run: npm run test
        working-directory: ./frontend

      - name: Build UI
        run: npm run build
        working-directory: ./frontend
