name: Deploy to Prod
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  deploy:
    env:
      NAMESPACE: prod
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies UI
        run: npm install
        working-directory: ./frontend

      - name: Run Linter
        run: npm run lint
        working-directory: ./frontend

      - name: Run UI Tests
        run: npm run test
        working-directory: ./frontend

      - name: Build UI
        run: npm run build
        working-directory: ./frontend

      - name: Install Dependencies CDK
        run: npm install
        working-directory: ./app

      - name: Build CDK
        run: npm run build
        working-directory: ./app

      - name: Deploy CDK
        run: npm run deploy
        working-directory: ./app
